---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-service
  labels:
    username: aoj19037
    env: test
spec:
  type: ClusterIP
  selector:
    app: redistestapp
  ports:
  - name: redis
    port: 6379
    targetPort: 6379