---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test-deployment
  labels:
    username: aoj19037
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redistestapp
  template:
    metadata:
    labels:
      username: aoj19037
      env: test
      app: redistestapp
     spec:
      containers:
        - name: redisContainer
	  labels:
	    username: aoj19037
            env: test
	    app:redistestapp
          imagePullPolicy: Always
          image: redis:7
	  volumeMounts:
	  - name: redis-data-pvc
	    mountPath: "/data"
	  ports:
          - name: redis
            containerPort: 6379
      volumes:
       - name: redis-data-pvc
         persistentVolumeClaim:
           claimName: redis-data-pvc       